# Welcome to Jekyll!
#

# Site settings
title: Megajuegos
description: |
  Un juego de tablero,  
  mezcla de Estrategia, Diplomacia y Negociación,  
  para 50 o más jugadores simultáneos.
owner: Megajuegos Argentina # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: megajuegos@protocultura.net
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.megajuegos.com.ar" # the base hostname & protocol for your site

currentgame:
  eventbrite-fullurl: https://www.eventbrite.com.ar/e/vigilen-los-cielos-60-tickets-713385393917
  eventbrite-id: 713385393917

# --- VLC
  descripcion: Reservá tu lugar para jugar "Vigilen los Cielos", nuestra localización del famoso Megajuego de terror global y encuentros cercanos, creado por Jim Wallman. Se realizará en forma presencial en la Ciudad de Buenos Aires, el 1ro de Octubre de 2023
  manual-url: manuales/VLC-Manual-Humanos-v5.3.pdf

# --- independencia
# descripcion: Reservá tu lugar para jugar online Independencia 1.0v el 26 de Junio de 2021, adquiriendo tu entrada acá
# manual-url: https://drive.google.com/file/d/1LYYVhVae_TIMchBFrm12HwQlVfTB_qLu/view?usp=sharing

# --- entente
# descripcion: Reservá tu lugar para jugar "Entente: Un vals Político", nuestro Megajuego ambientado en los años previos a la Primera Guerra Mundial y diseñado por Peter Nixon y Minnesota Megagames, de forma presencial el 23 de Julio de 2023
# manual-url: https://docs.google.com/document/d/1XQeDuZw0EhqntVZuiczoKZny8yPvJiK2VMhECs37mqg/edit?usp=sharing

# --- conquistar o morir
# descripcion: Reservá tu lugar para jugar "Conquistar o Morir", nuestro nuevo Megajuego inspirado en los libros de Game of Thrones, de forma presencial el 13 de Noviembre de 2022
# manual-url: https://drive.google.com/file/d/1MasgvZ_BWzfP0bkXVepd8i1jyn_zcOkB/view

social:
  twitter: https://twitter.com/megajuegosARG
  github: https://github.com/megajuegos/megajuegos.github.io
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/megajuegosARG
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: https://docs.google.com/forms/d/e/1FAIpQLSe5oe0Mq9vfZJVksNFqIZdDj7fBVPp98x80NF6I1kplxBd9gw/viewform
  #flickr:
  instagram: https://www.instagram.com/megajuegos_arg
  telegram: https://t.me/Megajugadores
  forumbee: https://t.me/Megajugadores
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
